
import "./src/styles/global.scss"
import "./src/styles/header.scss"
import "./src/styles/capabilities.scss"
import "./src/styles/practiceAreas.scss"
import "./src/styles/whyUs.scss"
import "./src/styles/about.scss"
import "./src/styles/contact.scss"
import "./src/styles/footer.scss"
import "./src/styles/callBar.scss"
import "./src/styles/attorneyProfile.scss"
import "./src/styles/singlePage.scss"
